import Head from "next/head";
import { Inter } from "next/font/google";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import { CardActionArea } from "@mui/material";
const inter = Inter({ subsets: ["latin"] });

interface IAwards {
  wins: Number;
  nominations: Number;
  text: String;
}
interface IMovie {
  _id: string;
  plot: String;
  genres: [String];
  runtime: Number;
  cast: [String];
  num_mflix_comments: Number;
  poster: string;
  title: String;
  fullplot: String;
  countries: [String];
  released: Date;
  directors: [String];
  writers: [String];
  awards: IAwards;
  lastupdated: String;
  year: Number;
  imdb: {
    rating: Number;
    votes: Number;
    id: Number;
  };
  type: String;
  tomatoes: {
    viewer: {
      rating: Number;
      numReviews: Number;
    };
    lastUpdated: Date;
  };
}

interface IMovies {
  movies: IMovie[];
}
export default function Home({ movies }: IMovies) {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-blue-900 min-h-screen">
        <div className="container mx-auto">
          <h1 className="font-bold text-white text-center text-5xl mb-10 ">
            Movies List
          </h1>
          <div className="grid grid-cols-4 gap-4 p-4">
            {movies.length > 0 &&
              movies.map((movie: IMovie, index) => (
                <Card sx={{ maxWidth: 250, height: 500 }} key={index}>
                  <CardActionArea>
                    <CardMedia
                      component="img"
                      height="140"
                      image={movie.poster}
                      alt=""
                    />
                    <CardContent>
                      <Typography gutterBottom variant="h5" component="div">
                        {movie.title}
                      </Typography>
                    </CardContent>
                  </CardActionArea>
                </Card>
              ))}
          </div>
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:8000/movies");
  const data = await res.json();

  return {
    props: { movies: data.movies },
  };
}
