import Head from "next/head";
import { Inter } from "next/font/google";
import Movie from "../Components/Movie";
import { Container } from "@mui/material";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AZURE Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <h1>Hello Azure-Next</h1>
          <Movie />
        </Container>
      </main>
    </>
  );
}
